services:
  - type: web
    name: tkapi
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        sync: false
      - key: HASH_SECRET
        sync: false
      - key: TIKTOK_CLIENT_KEY
        sync: false
      - key: TIKTOK_CLIENT_SECRET
        sync: false
      - key: TIKTOK_REDIRECT_URI
        value: https://tkapi.onrender.com/api/tiktok/callback
      - key: TIKTOK_SCOPES
        value: user.info.basic,video.list
